apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: kwv977yya-go
  janus-idp.io/tekton: kwv977yya-go
  backstage.io/kubernetes-id: kwv977yya-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kwv977yya-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
